services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=invoiceiq
      - MONGODB_COLLECTION_NAME=invoices
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_PORT=1433
      - SQLSERVER_DATABASE=invoiceiq
      - SQLSERVER_USERNAME=sa
      - SQLSERVER_PASSWORD=${SQLSERVER_PASSWORD}
      - SQLSERVER_DRIVER=ODBC Driver 18 for SQL Server
    depends_on:
      - mongo
      - sqlserver
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQLSERVER_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  mongo_data:
  sqlserver_data: